import { Inter } from 'next/font/google'
import './globals.css'
import { GlobalStorage } from '../components/Global'


const inter = Inter({ subsets: ['latin'] })
export const metadata = {
  title: 'Create Next App',
  description: 'Generated by create next app',
}

export default function RootLayout({ children }) {

  
  return (
    <html lang="en">
      <GlobalStorage>
        <body className={`${inter.className} max-w-screen h-screen px-0 sm:px-40 bg-[#FFFFFF]`}>
          {children}
        </body>
        </GlobalStorage>
    </html>
  )
}
