# Exemplo de fluxo de trabalho para construir e implantar um site Next.js nas páginas do GitHub
#
# Para começar com Next.js, consulte: https://nextjs.org/docs/getting-started
#
nome: Verifique a compilação do NextJs

sobre:
  # Executa em pushes direcionados ao branch padrão
  empurrar:
    filiais: ["principal"]
    
  # Executa em qualquer solicitação pull aberta ou reaberta
  pull_request:
    tipos: [aberto, reaberto]

  # Permite que você execute este fluxo de trabalho manualmente na guia Ações
  fluxo de trabalho_dispatch:

ambiente:
  API_KEY: ${{ secrets.API_KEY }}

# Define permissões do GITHUB_TOKEN para permitir a implantação nas páginas do GitHub
permissões:
  conteúdo: leia
  páginas: escrever
  token de identificação: escrever

empregos:
  # Construir trabalho
  construir:
    executado: ubuntu-mais recente
    passos:
      - nome: Check-out
        usa: ações/checkout@v4
      - nome: Detectar gerenciador de pacotes
        id: detect-package-manager
        executar: |
          se [ -f "${{ github.workspace }}/yarn.lock" ]; então
            echo "manager=yarn" >> $GITHUB_OUTPUT
            echo "comando=instalar" >> $GITHUB_OUTPUT
            echo "corredor=fio" >> $GITHUB_OUTPUT
            saída 0
          elif [ -f "${{ github.workspace }}/package.json" ]; então
            echo "manager=npm" >> $GITHUB_OUTPUT
            echo "command=ci" >> $GITHUB_OUTPUT
            echo "runner=npx --no-install" >> $GITHUB_OUTPUT
            saída 0
          outro
            echo "Não foi possível determinar o gerenciador de pacotes" >&2
            saída 1
          fi
      - nome: Nó de configuração
        usa: ações/setup-node@v3
        com:
          versão do nó: "20"
          cache: ${{steps.detect-package-manager.outputs.manager }}
      - nome: Restaurar cache
        usa: ações/cache@v3
        com:
          caminho: |
            .próximo/cache
          # Gere um novo cache sempre que pacotes ou arquivos de origem forem alterados.
          chave: ${{ runner.os }}-nextjs-${{ hashFiles('**/package-lock.json', '**/yarn.lock') }}-${{ hashFiles('**. [jt]s', '**.[jt]sx') }}
          # Se os arquivos de origem foram alterados, mas os pacotes não, reconstrua a partir de um cache anterior.
          chaves de restauração: |
            ${{ runner.os }}-nextjs-${{ hashFiles('**/package-lock.json', '**/yarn.lock') }}-
      - nome: Instalar dependências
        execute: ${{steps.detect-package-manager.outputs.manager }} ${{steps.detect-package-manager.outputs.command }}
      - nome: Construir com Next.js
        executar: npm executar compilação
